#############################################################################
# Makefile for building: PlaneTracker.app/Contents/MacOS/PlaneTracker
# Generated by qmake (2.01a) (Qt 4.8.3) on: Thu Jan 17 18:42:12 2013
# Project:  PlaneTracker.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile PlaneTracker.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DTHERON_BOOST -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -isystem /usr/local/include/decklink -O2 -std=c++11 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.3/mkspecs/macx-g++ -I. -I/usr/local/Cellar/qt/4.8.3/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.3/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.3/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.3/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.3/include -I/usr/local/include/External -I../opencv_trunk/include/opencv -I.moc -Isrc/ui -F/usr/local/Cellar/qt/4.8.3/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.8.3/lib -L/usr/local/Cellar/qt/4.8.3/lib `pkg-config opencv cvblob --cflags --libs` -lopencv_core -lboost_system-mt -lboost_iostreams-mt -ltherond -lboost_date_time-mt -lboost_thread-mt -lboost_program_options-mt -lopencv_highgui -lopencv_imgproc -lm -lpthread -framework CoreFoundation -framework QtGui -L/usr/local/Cellar/qt/4.8.3/lib -F/usr/local/Cellar/qt/4.8.3/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/util/Log.cpp \
		src/vision/FrameAnalyzerActor.cpp \
		src/gps/GPSReceiverInterface.cpp \
		src/gps/GeoReference.cpp \
		src/gps/GeoreferencingActor.cpp \
		src/util/Messages.cpp \
		src/main/MultimodalActor.cpp \
		src/gps/Protocol.cpp \
		src/vision/VideoReceiverInterface.cpp \
		src/vision/Vision.cpp \
		src/ui/ui.cpp \
		src/ui/imageview.cpp \
		src/main/tracker.cpp .moc/moc_ui.cpp \
		.moc/moc_imageview.cpp
OBJECTS       = obj/Log.o \
		obj/FrameAnalyzerActor.o \
		obj/GPSReceiverInterface.o \
		obj/GeoReference.o \
		obj/GeoreferencingActor.o \
		obj/Messages.o \
		obj/MultimodalActor.o \
		obj/Protocol.o \
		obj/VideoReceiverInterface.o \
		obj/Vision.o \
		obj/ui.o \
		obj/imageview.o \
		obj/tracker.o \
		obj/moc_ui.o \
		obj/moc_imageview.o
DIST          = /usr/local/Cellar/qt/4.8.3/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/g++-base.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.3/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/lex.prf \
		PlaneTracker.pro
QMAKE_TARGET  = PlaneTracker
DESTDIR       = 
TARGET        = PlaneTracker.app/Contents/MacOS/PlaneTracker

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile PlaneTracker.app/Contents/PkgInfo PlaneTracker.app/Contents/Resources/empty.lproj PlaneTracker.app/Contents/Info.plist $(TARGET)

$(TARGET): src/ui/ui_ui.h src/ui/ui_imageview.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) PlaneTracker.app/Contents/MacOS/ || $(MKDIR) PlaneTracker.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PlaneTracker.pro  /usr/local/Cellar/qt/4.8.3/mkspecs/macx-g++/qmake.conf /usr/local/Cellar/qt/4.8.3/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/g++-base.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.3/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.3/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.8.3/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile PlaneTracker.pro
/usr/local/Cellar/qt/4.8.3/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.3/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.3/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.3/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.3/mkspecs/common/g++-base.conf:
/usr/local/Cellar/qt/4.8.3/mkspecs/common/g++-macx.conf:
/usr/local/Cellar/qt/4.8.3/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.3/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.3/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.8.3/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile PlaneTracker.pro

PlaneTracker.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) PlaneTracker.app/Contents || $(MKDIR) PlaneTracker.app/Contents 
	@$(DEL_FILE) PlaneTracker.app/Contents/PkgInfo
	@echo "APPL????" >PlaneTracker.app/Contents/PkgInfo
PlaneTracker.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) PlaneTracker.app/Contents/Resources || $(MKDIR) PlaneTracker.app/Contents/Resources 
	@touch PlaneTracker.app/Contents/Resources/empty.lproj
	
PlaneTracker.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) PlaneTracker.app/Contents || $(MKDIR) PlaneTracker.app/Contents 
	@$(DEL_FILE) PlaneTracker.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,PlaneTracker,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/4.8.3/mkspecs/macx-g++/Info.plist.app >PlaneTracker.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) obj/PlaneTracker1.0.0 || $(MKDIR) obj/PlaneTracker1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/PlaneTracker1.0.0/ && $(COPY_FILE) --parents src/util/Log.h src/vision/FrameAnalyzerActor.h src/gps/GPSReceiverInterface.h src/gps/GeoReference.h src/gps/GeoreferencingActor.h src/util/Messages.h src/main/MultimodalActor.h src/gps/Protocol.h src/vision/VideoReceiverInterface.h src/vision/Vision.h src/ui/ui.h src/ui/imageview.h obj/PlaneTracker1.0.0/ && $(COPY_FILE) --parents src/util/Log.cpp src/vision/FrameAnalyzerActor.cpp src/gps/GPSReceiverInterface.cpp src/gps/GeoReference.cpp src/gps/GeoreferencingActor.cpp src/util/Messages.cpp src/main/MultimodalActor.cpp src/gps/Protocol.cpp src/vision/VideoReceiverInterface.cpp src/vision/Vision.cpp src/ui/ui.cpp src/ui/imageview.cpp src/main/tracker.cpp obj/PlaneTracker1.0.0/ && $(COPY_FILE) --parents src/ui/ui.ui src/ui/imageview.ui obj/PlaneTracker1.0.0/ && (cd `dirname obj/PlaneTracker1.0.0` && $(TAR) PlaneTracker1.0.0.tar PlaneTracker1.0.0 && $(COMPRESS) PlaneTracker1.0.0.tar) && $(MOVE) `dirname obj/PlaneTracker1.0.0`/PlaneTracker1.0.0.tar.gz . && $(DEL_FILE) -r obj/PlaneTracker1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r PlaneTracker.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: .moc/moc_ui.cpp .moc/moc_imageview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_ui.cpp .moc/moc_imageview.cpp
.moc/moc_ui.cpp: src/ui/ui.h
	/usr/local/Cellar/qt/4.8.3/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/ui/ui.h -o .moc/moc_ui.cpp

.moc/moc_imageview.cpp: src/util/Messages.h \
		src/ui/imageview.h
	/usr/local/Cellar/qt/4.8.3/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/ui/imageview.h -o .moc/moc_imageview.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: src/ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) src/ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: src/ui/ui_ui.h src/ui/ui_imageview.h
compiler_uic_clean:
	-$(DEL_FILE) src/ui/ui_ui.h src/ui/ui_imageview.h
src/ui/ui_ui.h: src/ui/ui.ui
	/usr/local/Cellar/qt/4.8.3/bin/uic src/ui/ui.ui -o src/ui/ui_ui.h

src/ui/ui_imageview.h: src/ui/imageview.ui
	/usr/local/Cellar/qt/4.8.3/bin/uic src/ui/imageview.ui -o src/ui/ui_imageview.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/Log.o: src/util/Log.cpp src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Log.o src/util/Log.cpp

obj/FrameAnalyzerActor.o: src/vision/FrameAnalyzerActor.cpp src/vision/FrameAnalyzerActor.h \
		src/util/Messages.h \
		src/vision/Vision.h \
		src/perhaps/perhaps.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/FrameAnalyzerActor.o src/vision/FrameAnalyzerActor.cpp

obj/GPSReceiverInterface.o: src/gps/GPSReceiverInterface.cpp src/gps/GPSReceiverInterface.h \
		src/util/Messages.h \
		src/gps/Protocol.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GPSReceiverInterface.o src/gps/GPSReceiverInterface.cpp

obj/GeoReference.o: src/gps/GeoReference.cpp src/gps/GeoReference.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GeoReference.o src/gps/GeoReference.cpp

obj/GeoreferencingActor.o: src/gps/GeoreferencingActor.cpp src/gps/GeoreferencingActor.h \
		src/util/Messages.h \
		src/gps/GeoReference.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GeoreferencingActor.o src/gps/GeoreferencingActor.cpp

obj/Messages.o: src/util/Messages.cpp src/util/Messages.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Messages.o src/util/Messages.cpp

obj/MultimodalActor.o: src/main/MultimodalActor.cpp src/main/MultimodalActor.h \
		src/util/Messages.h \
		src/util/Log.h \
		src/gps/Protocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/MultimodalActor.o src/main/MultimodalActor.cpp

obj/Protocol.o: src/gps/Protocol.cpp src/gps/Protocol.h \
		src/util/Messages.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Protocol.o src/gps/Protocol.cpp

obj/VideoReceiverInterface.o: src/vision/VideoReceiverInterface.cpp src/vision/VideoReceiverInterface.h \
		src/util/Messages.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/VideoReceiverInterface.o src/vision/VideoReceiverInterface.cpp

obj/Vision.o: src/vision/Vision.cpp src/vision/Vision.h \
		src/util/Messages.h \
		src/perhaps/perhaps.h \
		src/util/Log.h \
		src/perhaps/fun.cpp \
		src/perhaps/fun.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Vision.o src/vision/Vision.cpp

obj/ui.o: src/ui/ui.cpp src/util/Log.h \
		src/util/Messages.h \
		src/vision/FrameAnalyzerActor.h \
		src/vision/Vision.h \
		src/perhaps/perhaps.h \
		src/gps/GeoreferencingActor.h \
		src/main/MultimodalActor.h \
		src/ui/ui.h \
		src/ui/ui_ui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ui.o src/ui/ui.cpp

obj/imageview.o: src/ui/imageview.cpp src/ui/imageview.h \
		src/util/Messages.h \
		src/ui/ui_imageview.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/imageview.o src/ui/imageview.cpp

obj/tracker.o: src/main/tracker.cpp src/gps/GPSReceiverInterface.h \
		src/util/Messages.h \
		src/gps/GeoreferencingActor.h \
		src/main/MultimodalActor.h \
		src/util/Log.h \
		src/vision/FrameAnalyzerActor.h \
		src/vision/Vision.h \
		src/perhaps/perhaps.h \
		src/vision/VideoReceiverInterface.h \
		src/ui/ui.h \
		src/ui/imageview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tracker.o src/main/tracker.cpp

obj/moc_ui.o: .moc/moc_ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_ui.o .moc/moc_ui.cpp

obj/moc_imageview.o: .moc/moc_imageview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_imageview.o .moc/moc_imageview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

