#############################################################################
# Makefile for building: PlaneTracker
# Generated by qmake (2.01a) (Qt 4.8.4) on: Sun Apr 21 22:03:00 2013
# Project:  PlaneTracker.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile PlaneTracker.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../Theron-5.01.01/Include -I/usr/include/opencv -I.moc -Isrc/ui
LINK          = g++
LFLAGS        = -m64 -Wl,-O1,--sort-common,--as-needed,-z,relro
LIBS          = $(SUBLIBS)  -L/usr/lib `pkg-config opencv cvblob --cflags --libs` -lopencv_core -lboost_system -lboost_iostreams -ltherond -lboost_date_time -lboost_thread -lboost_program_options -lopencv_highgui -lopencv_imgproc -lm -L/home/atom/Theron-5.01.01/Lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/util/Log.cpp \
		src/vision/FrameAnalyzerActor.cpp \
		src/gps/GPSReceiverInterface.cpp \
		src/gps/GeoReference.cpp \
		src/gps/GeoreferencingActor.cpp \
		src/util/Messages.cpp \
		src/main/MultimodalActor.cpp \
		src/gps/Protocol.cpp \
		src/vision/VideoReceiverInterface.cpp \
		src/vision/Vision.cpp \
		src/ui/ui.cpp \
		src/ui/imageview.cpp \
		src/main/tracker.cpp .moc/moc_ui.cpp \
		.moc/moc_imageview.cpp
OBJECTS       = obj/Log.o \
		obj/FrameAnalyzerActor.o \
		obj/GPSReceiverInterface.o \
		obj/GeoReference.o \
		obj/GeoreferencingActor.o \
		obj/Messages.o \
		obj/MultimodalActor.o \
		obj/Protocol.o \
		obj/VideoReceiverInterface.o \
		obj/Vision.o \
		obj/ui.o \
		obj/imageview.o \
		obj/tracker.o \
		obj/moc_ui.o \
		obj/moc_imageview.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		PlaneTracker.pro
QMAKE_TARGET  = PlaneTracker
DESTDIR       = 
TARGET        = PlaneTracker

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): src/ui/ui_ui.h src/ui/ui_imageview.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: PlaneTracker.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile PlaneTracker.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile PlaneTracker.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/PlaneTracker1.0.0 || $(MKDIR) obj/PlaneTracker1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/PlaneTracker1.0.0/ && $(COPY_FILE) --parents src/util/Log.h src/vision/FrameAnalyzerActor.h src/gps/GPSReceiverInterface.h src/gps/GeoReference.h src/gps/GeoreferencingActor.h src/util/Messages.h src/main/MultimodalActor.h src/gps/Protocol.h src/vision/VideoReceiverInterface.h src/vision/Vision.h src/ui/ui.h src/ui/imageview.h obj/PlaneTracker1.0.0/ && $(COPY_FILE) --parents src/util/Log.cpp src/vision/FrameAnalyzerActor.cpp src/gps/GPSReceiverInterface.cpp src/gps/GeoReference.cpp src/gps/GeoreferencingActor.cpp src/util/Messages.cpp src/main/MultimodalActor.cpp src/gps/Protocol.cpp src/vision/VideoReceiverInterface.cpp src/vision/Vision.cpp src/ui/ui.cpp src/ui/imageview.cpp src/main/tracker.cpp obj/PlaneTracker1.0.0/ && $(COPY_FILE) --parents src/ui/ui.ui src/ui/imageview.ui obj/PlaneTracker1.0.0/ && (cd `dirname obj/PlaneTracker1.0.0` && $(TAR) PlaneTracker1.0.0.tar PlaneTracker1.0.0 && $(COMPRESS) PlaneTracker1.0.0.tar) && $(MOVE) `dirname obj/PlaneTracker1.0.0`/PlaneTracker1.0.0.tar.gz . && $(DEL_FILE) -r obj/PlaneTracker1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .moc/moc_ui.cpp .moc/moc_imageview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_ui.cpp .moc/moc_imageview.cpp
.moc/moc_ui.cpp: src/ui/ui.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/ui/ui.h -o .moc/moc_ui.cpp

.moc/moc_imageview.cpp: src/util/Messages.h \
		src/ui/imageview.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/ui/imageview.h -o .moc/moc_imageview.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: src/ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) src/ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: src/ui/ui_ui.h src/ui/ui_imageview.h
compiler_uic_clean:
	-$(DEL_FILE) src/ui/ui_ui.h src/ui/ui_imageview.h
src/ui/ui_ui.h: src/ui/ui.ui
	/usr/lib/qt4/bin/uic src/ui/ui.ui -o src/ui/ui_ui.h

src/ui/ui_imageview.h: src/ui/imageview.ui
	/usr/lib/qt4/bin/uic src/ui/imageview.ui -o src/ui/ui_imageview.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/Log.o: src/util/Log.cpp src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Log.o src/util/Log.cpp

obj/FrameAnalyzerActor.o: src/vision/FrameAnalyzerActor.cpp src/vision/FrameAnalyzerActor.h \
		src/util/Messages.h \
		src/vision/Vision.h \
		src/perhaps/perhaps.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/FrameAnalyzerActor.o src/vision/FrameAnalyzerActor.cpp

obj/GPSReceiverInterface.o: src/gps/GPSReceiverInterface.cpp src/gps/GPSReceiverInterface.h \
		src/util/Messages.h \
		src/gps/Protocol.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GPSReceiverInterface.o src/gps/GPSReceiverInterface.cpp

obj/GeoReference.o: src/gps/GeoReference.cpp src/gps/GeoReference.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GeoReference.o src/gps/GeoReference.cpp

obj/GeoreferencingActor.o: src/gps/GeoreferencingActor.cpp src/gps/GeoreferencingActor.h \
		src/util/Messages.h \
		src/gps/GeoReference.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GeoreferencingActor.o src/gps/GeoreferencingActor.cpp

obj/Messages.o: src/util/Messages.cpp src/util/Messages.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Messages.o src/util/Messages.cpp

obj/MultimodalActor.o: src/main/MultimodalActor.cpp src/main/MultimodalActor.h \
		src/util/Messages.h \
		src/util/Log.h \
		src/gps/Protocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/MultimodalActor.o src/main/MultimodalActor.cpp

obj/Protocol.o: src/gps/Protocol.cpp src/gps/Protocol.h \
		src/util/Messages.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Protocol.o src/gps/Protocol.cpp

obj/VideoReceiverInterface.o: src/vision/VideoReceiverInterface.cpp src/vision/VideoReceiverInterface.h \
		src/util/Messages.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/VideoReceiverInterface.o src/vision/VideoReceiverInterface.cpp

obj/Vision.o: src/vision/Vision.cpp src/vision/Vision.h \
		src/util/Messages.h \
		src/perhaps/perhaps.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Vision.o src/vision/Vision.cpp

obj/ui.o: src/ui/ui.cpp src/util/Log.h \
		src/util/Messages.h \
		src/vision/FrameAnalyzerActor.h \
		src/vision/Vision.h \
		src/perhaps/perhaps.h \
		src/gps/GeoreferencingActor.h \
		src/main/MultimodalActor.h \
		src/ui/ui.h \
		src/ui/ui_ui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ui.o src/ui/ui.cpp

obj/imageview.o: src/ui/imageview.cpp src/ui/imageview.h \
		src/util/Messages.h \
		src/ui/ui_imageview.h \
		src/util/Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/imageview.o src/ui/imageview.cpp

obj/tracker.o: src/main/tracker.cpp src/gps/GPSReceiverInterface.h \
		src/util/Messages.h \
		src/gps/GeoreferencingActor.h \
		src/main/MultimodalActor.h \
		src/util/Log.h \
		src/vision/FrameAnalyzerActor.h \
		src/vision/Vision.h \
		src/perhaps/perhaps.h \
		src/vision/VideoReceiverInterface.h \
		src/ui/ui.h \
		src/ui/imageview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tracker.o src/main/tracker.cpp

obj/moc_ui.o: .moc/moc_ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_ui.o .moc/moc_ui.cpp

obj/moc_imageview.o: .moc/moc_imageview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_imageview.o .moc/moc_imageview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

